# 数据源的配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://159.75.116.209:3306/kss_category?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: feifeiya..
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 30
      minimum-idle: 10
      read-only: false
      # 禁用模板引擎缓存
  thymeleaf:
    cache: false
  spring:
    main:
      allow-bean-definition-overriding: true
    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      mode: HTML
      encoding: UTF-8
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
      locale: zh_CN
      # 解决json返回过程中long的精度丢失问题
      generator:
        write-numbers-as-strings: true
        write-bigdecimal-as-plain: true

  redis:
    database: 0
    password: feifeiya..
    host: 159.75.116.209
    port: 6379
  # 数据库连接配置

#redis的bloomfilter
redis:
  bloom:
    host: 159.75.116.209
    port: 6379
    password: feifeiya..
    capacity: 100
    rate: 0.01


#    日志配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    设置会话超时时间为15分钟

